version: '3.3'
services:
  arangodb:
    ports:
      - '8529:8529'
    image: 'arangodb/arangodb:3.8.2'
    volumes:
      - ${DB_MOUNT_LOCATION}/arangodb3:/var/lib/arangodb3
      - ${DB_MOUNT_LOCATION}/arangodb3-apps:/var/lib/arangodb3-apps
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
