name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - api/**
      - .github/**
  pull_request:
    branches: [ main ]
    paths:
      - api/**
      - .github/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        run: |
          ls -la
          
          
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: festivekyle/opentoolbox-api


      
