name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
      - .github/**
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**
      - .github/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: Create .env
      run: |
        cat << EOF > .env
        REACT_APP_API_ENDPOINT="${{ REACT_APP_API_ENDPOINT }}"
        EOF


    - name: Build
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/build

